### PR TITLE
feat: Introduce interactive update

### PR DESCRIPTION
**Pull request by KamiKillertO**
I think it could be nice to add a way to select the select to update.
This feature is inspired by `yarn upgrade-interactive`

It looks like this
Kapture 2019-10-10 at 15 14 15

### CODE REVIEW

**Comment by KamiKillertO** [comment]
I've updated the snapshots for the failing tests due to the changes I've introduced. There's still some tests failing tests, but I've checked and they also fail on `master`.

**Comment by KamiKillertO** [comment]
@jhnns what do you think about this feature ?

**Comment by jhnns** [comment]
Damn, I just saw this. I think it's a nice feature 👏

**Comment by KamiKillertO** [comment]
I accidentally closed it while trying a new plugin for the GitHub CLI 😅 .
I opened this long ago and thought the project was no longer maintained.

**Pull request merged**
