### PR TITLE
fix: yarn parse

### LINKED ISSUE #59: Unexpected token { in JSON
Just updated to 1.0.0 and got this error when running (Node v7.5.0):

```
❯ updtr
Looking for outdated modules... ⠲ undefined:2
{"type":"finished","data":978}
^

SyntaxError: Unexpected token { in JSON at position 922
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/updtr/lib/run.js:122:25
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### PR DESCRIPTION
**Pull request by GantMan**
I found an issue on counting the number of lines, due to possible multi-line JSON from tests.  So my solution isn't exactly as we had envisioned.  It's more of a try/catch due to how much better this fit.

I fixed up the code to attempt to parse the normal way, and then check for multiple objects IF the traditional method failed.  All code is stored in there, so npm doesn't take any kind of hit.  Sort of a fall-back and the final product is still very quick!

I still had failing tests, but it looked unrelated, as the test that was originally failing is now passing. Additionally, my manual test worked with yarn after this patch.

---
Fixes #59

### CODE REVIEW

**Comment by GantMan** [comment]
Side note, I'm not sure why those snap files came out when I ran tests.

**Comment by GantMan** [comment]
ping @jhnns - tests seem borked independent of this PR.

plz review/merge

**Comment by dash-** [comment]
I'd like to see something like this merged if it solves the bug - however, I'd recommend revising it so the snap file removals are not committed as part of this PR.  I can't see this being merged as is.

**Comment by GantMan** [comment]
I'm really not sure why the snaps are removed... will fix.

**Pull request closed without merging**
